/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ACORN_SYSTEM;
import DATA.DashModel;
import DATA.DashController;
import DATA.PasswordController;
import DATABASE.DatabaseHandler;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import javax.swing.JButton;
import javax.swing.SwingUtilities;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Clarence Miole
 */
public class DashView extends javax.swing.JFrame {
    
      private DashController controller;
      private PasswordController controllers;
      private Timer timer;
      private RegisterView view;
      private static Connection connection;
      private static String user;
      private DashModel model;
      private double totalPrice;
      private double payments;
      
    /**
     * Creates new form DashView
     * @param user
     */
   public DashView(String user) {
        this.user = user;
        initComponents();
         this.model= new DashModel(connection);
         
        setTitle("Acorn Dashboard");
        setLocationRelativeTo(null);
        timer = new Timer(1000, (var e) -> {
            updateTime();
            
        });
        timer.start();
        
        
        DashModel model = new DashModel(connection);
    controller = new DashController();
    }

        public JButton getCatButton() {
        return cat;
    }

    public JButton getCat1Button() {
        return cat1;
    }
    public JButton getCat2Button() {
        return cat2;
    }

    public JButton getCat3Button() {
        return cat3;
    }

    public JButton getCat4Button() {
        return cat4;
    }

    public void showTabs(String tabName) {
    switch (tabName) {
        case "CATEGORY" : DASHB.setSelectedComponent(CATEGORY);
        break;
        case "ABOUT US" : DASHB.setSelectedComponent(ABOUT);
        break;
        case "CART" : DASHB.setSelectedComponent(CART);
        break;
        case "PAYMENT" : DASHB.setSelectedComponent(PAYMENT);
        break;
        case "ACCOUNT": DASHB.setSelectedComponent(ACCOUNT);
        break;
        case "SINGLE": DASHB.setSelectedComponent(SINGLE);
        break;
        case "OTHERS": DASHB.setSelectedComponent(OTHERS);
        break;
        case "MULTI": DASHB.setSelectedComponent(MULTI);
        break;
        case "ENTER": DASHB.setSelectedComponent(ENTER);
        break;
        default: 
              break;
    }
}
    
 
    
    
     private void updateTime() {
        Date now = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat(" HH:mm:ss");
        String formattedTime = dateFormat.format(now);

        time.setText(formattedTime);
  
    }

public void setController(DashController controller) {
        this.controller = controller;
    }
  
private String getSelectedItemName() {
    // Implement this method to get the selected item name
    return "Selected Item Name";
}

private double getSelectedItemPrice() {
    // Implement this method to get the selected item price
    return 10.99;
}

private void resetTable() {
    // TODO: Implement logic to reset the table here
    // For example, if you have a table model, you can clear it:
    DefaultTableModel model = (DefaultTableModel) table.getModel();
    model.setRowCount(0);

    // Clear the total JTextField
    total.setText("");
}
  
private String date() {
    // You can customize this method based on how you want to retrieve the current date
    // Here, we are using the current system date as a placeholder
    return java.time.LocalDate.now().toString();
}   
  private void clearTextField() {
    quan.setText("");
    total.setText("");
    change.setText("");
   payment.setText("");
}
 private void clearTextFields() {
    product10.setText("");
    category10.setSelectedIndex(0); // Assuming the first item is a default or empty value
    price10.setText("");
    quantity10.setText("");
}
  

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        DASHB = new javax.swing.JTabbedPane();
        CATEGORY = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        single = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CART = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        reset = new javax.swing.JButton();
        del = new javax.swing.JButton();
        getpay = new javax.swing.JButton();
        select = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        ABOUT = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        PAYMENT = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pay = new javax.swing.JButton();
        payment = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        quan = new javax.swing.JTextField();
        change = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ACCOUNT = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        upduser = new javax.swing.JButton();
        updpass = new javax.swing.JButton();
        create = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        SINGLE = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        GoFbutton = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        MULTI = new javax.swing.JPanel();
        CODbutton = new javax.swing.JButton();
        Valorantbutton = new javax.swing.JButton();
        farlight84button = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ENTER = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        OTHERS = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cat2 = new javax.swing.JButton();
        cat3 = new javax.swing.JButton();
        cat1 = new javax.swing.JButton();
        cat4 = new javax.swing.JButton();
        time = new javax.swing.JLabel();
        cat = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        seladd10 = new javax.swing.JButton();
        product10 = new javax.swing.JTextField();
        price10 = new javax.swing.JTextField();
        category10 = new javax.swing.JComboBox<>();
        quantity10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        unsel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CATEGORY.setBackground(new java.awt.Color(225, 239, 237));
        CATEGORY.setPreferredSize(new java.awt.Dimension(1000, 300));
        CATEGORY.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel1.setText("Hot Deals");
        CATEGORY.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 164, 50));

        single.setBackground(new java.awt.Color(148, 174, 137));
        single.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        single.setText("Single Player");
        single.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        single.setPreferredSize(new java.awt.Dimension(230, 90));
        single.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleActionPerformed(evt);
            }
        });
        CATEGORY.add(single, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jButton2.setBackground(new java.awt.Color(148, 174, 137));
        jButton2.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jButton2.setText("Mutli-Player");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setPreferredSize(new java.awt.Dimension(230, 90));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        CATEGORY.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jButton3.setBackground(new java.awt.Color(148, 174, 137));
        jButton3.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jButton3.setText("Entertainment Apps");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setPreferredSize(new java.awt.Dimension(230, 90));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        CATEGORY.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        jButton4.setBackground(new java.awt.Color(148, 174, 137));
        jButton4.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jButton4.setText("Others");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setPreferredSize(new java.awt.Dimension(230, 90));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        CATEGORY.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));
        CATEGORY.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, 1000, 510));

        DASHB.addTab("DASHBOARD", CATEGORY);

        CART.setBackground(new java.awt.Color(225, 239, 237));
        CART.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Kristen ITC", 0, 36)); // NOI18N
        jLabel2.setText("Cart");
        CART.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 15, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quantity", "Product", "Price", "Category", "Date "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(table);

        CART.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 630, 250));

        reset.setBackground(new java.awt.Color(148, 174, 137));
        reset.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        reset.setText("Reset");
        reset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        CART.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 120, 50));

        del.setBackground(new java.awt.Color(148, 174, 137));
        del.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        del.setText("Delete");
        del.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        CART.add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 120, 50));

        getpay.setBackground(new java.awt.Color(148, 174, 137));
        getpay.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        getpay.setText("Pay");
        getpay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getpayActionPerformed(evt);
            }
        });
        CART.add(getpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 120, 50));

        select.setText("Select All");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        CART.add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ACORN_SYSTEM/new Skies and flower bg.png"))); // NOI18N
        CART.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, 1000, 510));

        DASHB.addTab("Cart", CART);

        ABOUT.setBackground(new java.awt.Color(225, 239, 237));
        ABOUT.setPreferredSize(new java.awt.Dimension(460, 467));
        ABOUT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(225, 239, 237));
        jLabel4.setFont(new java.awt.Font("Kristen ITC", 0, 36)); // NOI18N
        jLabel4.setText("About Us");
        ABOUT.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ACORN_SYSTEM/new Skies and flower bg.png"))); // NOI18N
        ABOUT.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, -1, 510));

        DASHB.addTab("ABOUT US", ABOUT);

        PAYMENT.setBackground(new java.awt.Color(225, 239, 237));
        PAYMENT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Kristen ITC", 0, 36)); // NOI18N
        jLabel3.setText("Payment");
        PAYMENT.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel10.setText("Enter Payment:");
        PAYMENT.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel11.setText("Total:");
        PAYMENT.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        jLabel12.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel12.setText("Quantity:");
        PAYMENT.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel13.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel13.setText("Change:");
        PAYMENT.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        pay.setBackground(new java.awt.Color(148, 174, 137));
        pay.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        pay.setText("Pay");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });
        PAYMENT.add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 100, 50));

        payment.setBackground(new java.awt.Color(148, 174, 137));
        payment.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        payment.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentActionPerformed(evt);
            }
        });
        PAYMENT.add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 300, 50));

        total.setBackground(new java.awt.Color(148, 174, 137));
        total.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        total.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        total.setEnabled(false);
        total.setFocusable(false);
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        PAYMENT.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 300, 50));

        quan.setBackground(new java.awt.Color(148, 174, 137));
        quan.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        quan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        quan.setEnabled(false);
        quan.setFocusable(false);
        PAYMENT.add(quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 300, 50));

        change.setBackground(new java.awt.Color(148, 174, 137));
        change.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        change.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        change.setEnabled(false);
        change.setFocusable(false);
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });
        PAYMENT.add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 300, 50));
        PAYMENT.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, 1000, 510));

        DASHB.addTab("Payment", PAYMENT);

        ACCOUNT.setBackground(new java.awt.Color(225, 239, 237));
        ACCOUNT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Kristen ITC", 0, 36)); // NOI18N
        jLabel5.setText("Account");
        ACCOUNT.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        logout.setBackground(new java.awt.Color(148, 174, 137));
        logout.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Log Out");
        logout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        logout.setPreferredSize(new java.awt.Dimension(168, 27));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        ACCOUNT.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 200, 60));

        delete.setBackground(new java.awt.Color(148, 174, 137));
        delete.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete Account");
        delete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        delete.setPreferredSize(new java.awt.Dimension(168, 27));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        ACCOUNT.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 200, 60));

        upduser.setBackground(new java.awt.Color(148, 174, 137));
        upduser.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        upduser.setForeground(new java.awt.Color(255, 255, 255));
        upduser.setText("Update Username");
        upduser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        upduser.setPreferredSize(new java.awt.Dimension(168, 27));
        upduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upduserActionPerformed(evt);
            }
        });
        ACCOUNT.add(upduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 200, 60));

        updpass.setBackground(new java.awt.Color(148, 174, 137));
        updpass.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        updpass.setForeground(new java.awt.Color(255, 255, 255));
        updpass.setText("Update Password");
        updpass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        updpass.setPreferredSize(new java.awt.Dimension(168, 27));
        updpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updpassActionPerformed(evt);
            }
        });
        ACCOUNT.add(updpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 200, 60));

        create.setBackground(new java.awt.Color(148, 174, 137));
        create.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        create.setForeground(new java.awt.Color(255, 255, 255));
        create.setText("Create New Account");
        create.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        ACCOUNT.add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 200, 60));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ACORN_SYSTEM/new Skies and flower bg.png"))); // NOI18N
        ACCOUNT.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, 1000, 510));

        DASHB.addTab("Account", ACCOUNT);

        SINGLE.setBackground(new java.awt.Color(225, 239, 237));
        SINGLE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Kristen ITC", 0, 36)); // NOI18N
        jLabel23.setText("Single-Player Apps");
        SINGLE.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        GoFbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoFbuttonActionPerformed(evt);
            }
        });
        SINGLE.add(GoFbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 120, 200));
        SINGLE.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 120, 200));

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        SINGLE.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 120, 200));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ACORN_SYSTEM/new Skies and flower bg.png"))); // NOI18N
        SINGLE.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, 1000, 510));

        DASHB.addTab("SINGLE", SINGLE);

        MULTI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CODbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CODbuttonActionPerformed(evt);
            }
        });
        MULTI.add(CODbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 120, 200));
        MULTI.add(Valorantbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 120, 200));
        MULTI.add(farlight84button, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 120, 200));

        jLabel26.setFont(new java.awt.Font("Kristen ITC", 0, 36)); // NOI18N
        jLabel26.setText("Multi-Player Apps");
        MULTI.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ACORN_SYSTEM/new Skies and flower bg.png"))); // NOI18N
        MULTI.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, 1010, 510));

        DASHB.addTab("MULTI", MULTI);

        ENTER.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Kristen ITC", 0, 36)); // NOI18N
        jLabel22.setText("Entertainment Apps");
        ENTER.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        ENTER.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 120, 200));
        ENTER.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 120, 200));

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        ENTER.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 120, 200));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ACORN_SYSTEM/new Skies and flower bg.png"))); // NOI18N
        ENTER.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, -1, 510));

        DASHB.addTab("ENTER", ENTER);

        OTHERS.setBackground(new java.awt.Color(225, 239, 237));
        OTHERS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        OTHERS.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 120, 200));
        OTHERS.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 120, 200));
        OTHERS.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 120, 200));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ACORN_SYSTEM/new Skies and flower bg.png"))); // NOI18N
        jLabel25.setText("jLabel25");
        OTHERS.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, 1000, 510));

        DASHB.addTab("OTHERS", OTHERS);

        jPanel2.add(DASHB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, -40, 780, 450));

        jPanel1.setBackground(new java.awt.Color(225, 239, 237));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cat2.setBackground(new java.awt.Color(148, 174, 137));
        cat2.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        cat2.setText("Cart");
        cat2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat2ActionPerformed(evt);
            }
        });
        jPanel1.add(cat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 100, 40));

        cat3.setBackground(new java.awt.Color(148, 174, 137));
        cat3.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        cat3.setText("Payment");
        cat3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat3ActionPerformed(evt);
            }
        });
        jPanel1.add(cat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 100, 40));

        cat1.setBackground(new java.awt.Color(148, 174, 137));
        cat1.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        cat1.setText("About Us");
        cat1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cat1.setPreferredSize(new java.awt.Dimension(106, 35));
        cat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat1ActionPerformed(evt);
            }
        });
        jPanel1.add(cat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 100, 40));

        cat4.setBackground(new java.awt.Color(148, 174, 137));
        cat4.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        cat4.setText("Account");
        cat4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cat4.setMaximumSize(new java.awt.Dimension(106, 35));
        cat4.setMinimumSize(new java.awt.Dimension(106, 35));
        cat4.setPreferredSize(new java.awt.Dimension(106, 35));
        cat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat4ActionPerformed(evt);
            }
        });
        jPanel1.add(cat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 100, 40));

        time.setBackground(new java.awt.Color(148, 174, 137));
        time.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        time.setText(" 00:00:00");
        time.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 100, 40));

        cat.setBackground(new java.awt.Color(148, 174, 137));
        cat.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        cat.setText("Category");
        cat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catActionPerformed(evt);
            }
        });
        jPanel1.add(cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 100, 40));

        jLabel7.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel7.setText("Acorn");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 40));

        name.setEditable(false);
        name.setBackground(new java.awt.Color(148, 174, 137));
        name.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        name.setEnabled(false);
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 190, 90));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 500));

        jPanel3.setBackground(new java.awt.Color(225, 239, 237));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seladd10.setBackground(new java.awt.Color(244, 236, 225));
        seladd10.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        seladd10.setText("Select and Add");
        seladd10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        seladd10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seladd10seladdActionPerformed(evt);
            }
        });
        jPanel3.add(seladd10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 140, 60));

        product10.setBackground(new java.awt.Color(244, 236, 225));
        product10.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        product10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        product10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product10ActionPerformed(evt);
            }
        });
        jPanel3.add(product10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 60));

        price10.setBackground(new java.awt.Color(244, 236, 225));
        price10.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        price10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.add(price10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 120, 60));

        category10.setBackground(new java.awt.Color(244, 236, 225));
        category10.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        category10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single Player Game", "Entertainment Apps", "Multiplayer Game", "Others" }));
        category10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        category10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category10ActionPerformed(evt);
            }
        });
        jPanel3.add(category10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 160, 60));

        quantity10.setBackground(new java.awt.Color(244, 236, 225));
        quantity10.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        quantity10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.add(quantity10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 30, 60));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ACORN_SYSTEM/Skies and Flowers 2.0.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 20));
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(-225, -414, 1010, 510));

        unsel.setText("Unselect");
        unsel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unselActionPerformed(evt);
            }
        });
        jPanel3.add(unsel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 100, 60));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 780, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed

    }//GEN-LAST:event_nameActionPerformed

    private void catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catActionPerformed
        this.showTabs("CATEGORY");
    }//GEN-LAST:event_catActionPerformed

    private void cat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat4ActionPerformed
        this.showTabs("ACCOUNT");
    }//GEN-LAST:event_cat4ActionPerformed

    private void cat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat3ActionPerformed
        this.showTabs("PAYMENT");
    }//GEN-LAST:event_cat3ActionPerformed

    private void cat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat2ActionPerformed
        this.showTabs("CART");
    }//GEN-LAST:event_cat2ActionPerformed

    private void cat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat1ActionPerformed
        this.showTabs("ABOUT US");
    }//GEN-LAST:event_cat1ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // Open the registration frame
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Confirm Logout", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Logged out Successfully", "Confirmed Logout", JOptionPane.INFORMATION_MESSAGE);

            // Open the login frame
            LoginView view = new LoginView();
            view.setVisible(true);

            // Close the current frame
            this.dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        RegisterView regview = new RegisterView();
        regview.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete your account?", "Confirm Account Deletion", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // Delete the account from the database
            controller.deleteAccount();

            // Display a message saying "Account successfully deleted"
            JOptionPane.showMessageDialog(this, "Account successfully deleted", "Account Deleted", JOptionPane.OK_OPTION);
            // Close the current frame and open the login frame
            LoginView view = new LoginView();
            view.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void upduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upduserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upduserActionPerformed

    private void updpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updpassActionPerformed
       PasswordView pass = new PasswordView(controllers);
        pass.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updpassActionPerformed

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeActionPerformed

    private void singleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleActionPerformed
        this.showTabs("SINGLE");
    }//GEN-LAST:event_singleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.showTabs("MULTI");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.showTabs("ENTER");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.showTabs("ENTER");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void getpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getpayActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();

        // Check if any row is selected
        if (table.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "No row selected. Please select a row.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Initialize total quantity and total price
        int totalQuantity = 0;
        double totalPrice = 0.0;

        for (int row = 0; row < tableModel.getRowCount(); row++) {
            try {
                // Assuming column indices (adjust according to your table structure)
                Object quantityObj = tableModel.getValueAt(row, 0);
                Object priceObj = tableModel.getValueAt(row, 2); // Adjust the column index

                // Convert quantity and price to appropriate types (assuming they are integers and doubles)
                int quantity = Integer.parseInt(quantityObj.toString());
                double price = Double.parseDouble(priceObj.toString());

                // Calculate total quantity and total price
                totalQuantity += quantity;
                totalPrice += quantity * price;
            } catch (NumberFormatException e) {
                // Handle the case where conversion to numbers fails
                System.err.println("Error converting quantity or price to numbers at row " + (row + 1));
            }
        }

        // Set the calculated values to the text fields
        quan.setText(String.valueOf(totalQuantity));
        total.setText(String.valueOf(totalPrice));

        // Display the result in a JOptionPane
        JOptionPane.showMessageDialog(this, "Total Quantity: " + totalQuantity + "\nTotal Price: " + totalPrice);
        JOptionPane.showMessageDialog(this, "Please Proceed on the Payment Tab");
    }//GEN-LAST:event_getpayActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        resetTable();
    }//GEN-LAST:event_resetActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();

        // Get the selected row index
        int selectedRowIndex = table.getSelectedRow();

        if (selectedRowIndex != -1) { // Check if a row is selected
            // Assuming column indices (adjust according to your table structure)
            Object productIdObj = tableModel.getValueAt(selectedRowIndex, 0);

            try {
                // Convert product ID to the appropriate type (assuming it's an integer)
                int productId = Integer.parseInt(productIdObj.toString());

                // Delete the product from the database
                model.deleteProduct(productId);

                // Remove the selected row from the table
                tableModel.removeRow(selectedRowIndex);

            } catch (NumberFormatException e) {
                // Handle the case where conversion to a number fails
                System.err.println("Error converting product ID to a number.");
            }
        } else {
            // Handle the case where no row is selected
            System.err.println("No row selected.");
        }

    }//GEN-LAST:event_delActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        try {
            double paymentAmount = Double.parseDouble(payment.getText());

            // Assuming you have a JTextField named "total" for displaying the total amount
            double totalAmount = Double.parseDouble(total.getText());

            // Calculate change
            double changed = paymentAmount - totalAmount;

            if (changed >= 0) {
                // Assuming you have a JTextField named "changeField" for displaying the change amount
                change.setText(String.valueOf(changed));

                // Show success message
                JOptionPane.showMessageDialog(this, "Payment successful! Change: " + changed, "Success", JOptionPane.INFORMATION_MESSAGE);

                // Clear text fields after a successful purchase
                clearTextField();
            } else {
                // Show error message for insufficient payment
                JOptionPane.showMessageDialog(this, "Insufficient payment. Please enter a valid amount.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            // Handle the case where the entered payment amount is not a valid double
            // You might want to show an error message or handle it according to your requirements
            e.printStackTrace(); // Print the exception details for debugging

            // Show failure message
            JOptionPane.showMessageDialog(this, "Invalid payment amount. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_payActionPerformed

    private void seladd10seladdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seladd10seladdActionPerformed
         // Check if the category is selected
    if (category10.getSelectedIndex() == -1) {
        // Display an error message if the category is not selected
        JOptionPane.showMessageDialog(this, "Please select a category.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Check if any of the text fields are empty
    if (product10.getText().isEmpty() || price10.getText().isEmpty() || quantity10.getText().isEmpty()) {
        // Display an error message if any of the fields are empty
        JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String Product = product10.getText();
    String Category = category10.getSelectedItem().toString();

    double totalPrice;
    try {
        totalPrice = Double.parseDouble(price10.getText()); // Convert the text to double
    } catch (NumberFormatException e) {
        // Handle the case where the text in the price field is not a valid double
        // Show an error message
        JOptionPane.showMessageDialog(this, "Invalid total price. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    int Quantity;
    try {
        Quantity = Integer.parseInt(quantity10.getText()); // Convert the text to double
    } catch (NumberFormatException e) {
        // Handle the case where the text in the quantity field is not a valid double
        // Show an error message
        JOptionPane.showMessageDialog(this, "Invalid quantity. Please enter a valid whole number.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Assuming you have a DefaultTableModel named "tableModel"
    DefaultTableModel tableModel = (DefaultTableModel) table.getModel(); // replace with your actual table model

    // Add the values to the table model
    tableModel.addRow(new Object[]{Quantity, Product, totalPrice, Category, date()});
    model.saveProduct(Quantity, Product, totalPrice, Category);

    // Clear text fields after adding to the table
    clearTextFields();

    // Show a success message
    JOptionPane.showMessageDialog(this, "Product added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_seladd10seladdActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void category10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_category10ActionPerformed

    private void product10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product10ActionPerformed

    private void CODbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CODbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CODbuttonActionPerformed

    private void GoFbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoFbuttonActionPerformed
product10.setText("God of War");
category10.setSelectedItem("Single Player Game"); // Corrected method
price10.setText(String.valueOf(1200.00));    
    }//GEN-LAST:event_GoFbuttonActionPerformed

    private void unselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unselActionPerformed
        product10.setText("");
    category10.setSelectedIndex(-1);
    price10.setText("");
    }//GEN-LAST:event_unselActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        int rowCount = table.getRowCount();

        if (rowCount > 0) {
            // If there are rows in the table, select all of them
            table.selectAll();
        } else {
            // Handle the case where there are no rows in the table
            System.err.println("No rows to select.");
        }
    }//GEN-LAST:event_selectActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> {
            DashModel model = new DashModel(connection);
        DashView view = new DashView(user);
        DashController controller = new DashController();

        // Simulate a successful login and initialize the view with the username
         // Replace with the actual username
      
        });
     }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ABOUT;
    private javax.swing.JPanel ACCOUNT;
    private javax.swing.JPanel CART;
    private javax.swing.JPanel CATEGORY;
    private javax.swing.JButton CODbutton;
    private javax.swing.JTabbedPane DASHB;
    private javax.swing.JPanel ENTER;
    private javax.swing.JButton GoFbutton;
    private javax.swing.JPanel MULTI;
    private javax.swing.JPanel OTHERS;
    private javax.swing.JPanel PAYMENT;
    private javax.swing.JPanel SINGLE;
    private javax.swing.JButton Valorantbutton;
    private javax.swing.JButton cat;
    private javax.swing.JButton cat1;
    private javax.swing.JButton cat2;
    private javax.swing.JButton cat3;
    private javax.swing.JButton cat4;
    private javax.swing.JComboBox<String> category10;
    private javax.swing.JTextField change;
    private javax.swing.JButton create;
    private javax.swing.JButton del;
    private javax.swing.JButton delete;
    private javax.swing.JButton farlight84button;
    private javax.swing.JButton getpay;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JTextField name;
    private javax.swing.JButton pay;
    private javax.swing.JTextField payment;
    private javax.swing.JTextField price10;
    private javax.swing.JTextField product10;
    private javax.swing.JTextField quan;
    private javax.swing.JTextField quantity10;
    private javax.swing.JButton reset;
    private javax.swing.JButton seladd10;
    private javax.swing.JCheckBox select;
    private javax.swing.JButton single;
    private javax.swing.JTable table;
    private javax.swing.JLabel time;
    private javax.swing.JTextField total;
    private javax.swing.JButton unsel;
    private javax.swing.JButton updpass;
    private javax.swing.JButton upduser;
    // End of variables declaration//GEN-END:variables
}

